List<String> categoryOptions = [
  'Accommodation',
  'Agriculture & Animal',
  'Automotive',
  'Business Services',
  'Construction',
  'Employment Services & Education',
  'Entertainment',
  'Environmental',
  'Financial Services',
  'Food & Dining',
  'Forestry Related',
  'Government Services',
  'Health Services',
  'Industry',
  'Media & Design',
  'Non-Profit Groups & Clubs',
  'Professional Services',
  'Real Estate',
  'Restaurant',
  'Retail Sales',
  'Technical',
  'Trades',
];
